#! DO NOT DELETE THE COMMENTS BELOW
#-fn-start
font_family          FiraCode Nerd Font
bold_font            FiraCode Nerd Font
italic_font          FiraCode Nerd Font
bold_italic_font     FiraCode Nerd Font
#-fn-end

font_size 10
force_ltr no

